baseURL = "https://verrchu.github.io/blog/"
locale = "en-us"
title = "Evgeniy Terekhin"
ignoreFiles = ['/target/', '/src/', '/examples/', '/fixtures/', 'Cargo\.(toml|lock)$']

[markup]
  [markup.goldmark.renderer]
    unsafe = true
  [markup.highlight]
    style = "github-dark"
    noClasses = true
    lineNos = false
