baseURL = "https://verrchu.github.io/blog/"
locale = "en-us"
title = "Blog"

[markup]
  [markup.goldmark.renderer]
    unsafe = true
  [markup.highlight]
    style = "github-dark"
    noClasses = true
    lineNos = false
